import psycopg2
from psycopg2 import sql

import sys
import pathlib

db_name = 'database_new'
db_user = 'postgres'
db_password = 'secret'
db_host = 'localhost'
db_port = '5432'

try:
    # connect to default database
    connection = psycopg2.connect(database="postgres", user="postgres", password=db_password)
    connection.autocommit = True

    cursor = connection.cursor()

    # drop database if exists
    try:
        cursor.execute(sql.SQL('DROP DATABASE {};').format(sql.Identifier(db_name)))
    except psycopg2.Error as e:
        print(f'Failed to drop database: {e}')

    # create database with users and product tables
    cursor.execute(sql.SQL('CREATE DATABASE {};').format(sql.Identifier(db_name)))

    # close main postgres database connection
    cursor.close
    connection.close()

    # open connection with new database
    connection = psycopg2.connect(database=db_name, user="postgres", password=db_password)
    connection.autocommit = True
    cursor = connection.cursor()

    cursor.execute(sql.SQL('''
        CREATE TABLE USERS (
            ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ROLE VARCHAR(50) NOT NULL,
            FULL_NAME VARCHAR(150) NOT NULL,
            LOGIN VARCHAR(100) NOT NULL UNIQUE,
            PASSWORD VARCHAR(100) NOT NULL
        );'''
    ))
    cursor.execute(sql.SQL('''
        CREATE TABLE PRODUCT (
            PRODUCT_ARTICLE VARCHAR(7) PRIMARY KEY,
            PRODUCT_NAME VARCHAR(100) NOT NULL,
            DESCRIPTION VARCHAR(100),
            MANUFACTURER VARCHAR(100),
            SUPPLIER VARCHAR(100) NOT NULL,
            PRICE DECIMAL(15,2) NOT NULL,
            UNIT VARCHAR(20) NOT NULL,
            STOCK_QUANTITY INTEGER NOT NULL
        );'''
    ))

    # fill in test data
    cursor.execute(sql.SQL('''
        INSERT INTO USERS VALUES (0, 'Администратор', 'Николай Алексеевич', 'bocha', '123'),
            (1, 'Пользователь', 'Васян Васянович', 'vasyan', '321');
        COMMIT;'''
    ))

    cursor.execute(sql.SQL('''
        INSERT INTO PRODUCT VALUES ('NB123', 'Ноутбук игровой ASUS ROG', 'Мощный игровой ноутбук...', 'ASUS', 'Дилижанс-СБ', 125999.99, 'шт', 5),
            ('ART0002', 'Мышь беспроводная', 'Беспроводная мышь с Bluetooth', 'Logitech', 'ИП Иванов', 2499.50, 'шт', 50);
        COMMIT;'''
    ))

    cursor.close
    connection.close()
except psycopg2.Error as e:
    print(e)
